### ISSUE TITLE
Uninitialised variable: HAL_SD_ConfigWideBusOperation

### ISSUE THREAD

**Issue by thyrrestrup** [STMicroelectronics/stm32h5xx_hal_driver#2]
https://github.com/STMicroelectronics/stm32h5xx_hal_driver/blob/b21b55fe8b05245d06c559a09a77edf5a0679a74/Src/stm32h5xx_hal_sd.c#L2373

`sdmmc_clk` should be initialised to `0U`

**Comment by KRASTM** [comment]
Hello @thyrrestrup,

Thank you for your report.

In fact, the variable "sdmmc_clk" shouldn't be initialized to 0U in the function HAL_SD_ConfigWideBusOperation() To comply to Rule 2.2_c of MISRA C:2012.
Otherwise, the value 0 assigned to "sdmmc_clk" will never be used, as it will be overwritten in one of the Lines below:
https://github.com/STMicroelectronics/stm32h5xx_hal_driver/blob/b21b55fe8b05245d06c559a09a77edf5a0679a74/Src/stm32h5xx_hal_sd.c#L2420-L2429

I Hope this clarified your point and allow me to close the issue.

With Regards

**Comment by thyrrestrup** [comment]
arm-none-eabi-gcc 13.2 complain that sdmmc_clk could be used uninitialized. So maybe this should be handled in a different manner then?

**Comment by KRASTM** [comment]
Hello @thyrrestrup,

After a double-check we confirm the issue.
Our Dev team has already spotted & fixed it, the fix will be available in the frame of the next release.
Below the details:

* The Local variable "sdmmc_clk" is kept **uninitialized**
* [These](https://github.com/STMicroelectronics/stm32h5xx_hal_driver/blob/b21b55fe8b05245d06c559a09a77edf5a0679a74/Src/stm32h5xx_hal_sd.c#L2420-L2429) lines of Code have been updated as follow 

```diff
    if (hsd->Instance == SDMMC1)
    {
      sdmmc_clk = HAL_RCCEx_GetPeriphCLKFreq(RCC_PERIPHCLK_SDMMC1);
    }
#if defined(SDMMC2)
-    else
+    else if (hsd->Instance == SDMMC2)
    {
      sdmmc_clk = HAL_RCCEx_GetPeriphCLKFreq(RCC_PERIPHCLK_SDMMC2);
    }
#endif /* SDMMC2 */
+    else
+    {
+      sdmmc_clk = 0U;
+    }
```

Thank you for your feedback, the issue will be kept open until the fix is published on GitHub.
Regards

**Comment by thyrrestrup** [comment]
Should this approach also be used in `HAL_SD_InitCard`?

**Comment by KRASTM** [comment]
Hello @Thyrrestrup,

It's not necessary to use the same approach, it's a choice. 

With regards.
