### ISSUE TITLE
HAL_UART_RECEPTION_TORTO declared, but not used. Why ?

### ISSUE THREAD

**Issue by Ku100vEvgen** [STMicroelectronics/stm32h5xx_hal_driver#5]
HAL_UART_RECEPTION_TORTO declared in stm32h5xx_hal_uart.h
but not used in stm32h5xx_hal_uart.c and stm32h5xx_hal_uart_ex.c
Why ?

**Comment by KRASTM** [comment]
Hello @Ku100vEvgen,

Thank you for the report.

In fact, **HAL_UART_RECEPTION_TORTO** and **HAL_UART_RECEPTION_TOCHARMATCH** are declared in stm32h5xx_hal_uart.h by Our Development team in order to be used later (Developpement expectation). But unfortunately, we do not have a date yet.

With regards.

**Comment by KRASTM** [comment]
Hello @Ku100vEvgen,

Please, allow me to close this issue.

With regards,
